library(devtools)
# install_github("devtools", "hadley")
# install_github("slidify", "ramnathv")
# install_github("slidifyLibraries", "ramnathv")
# install_github("knitr", "yihui")
# install_github("whisker", "edwindj")
# install_github("markdown", "rstudio")
# install_github("ggthemes", "jrnold")
library(whisker)
library(slidify)
library(markdown)
library(slidifyLibraries)
library(knitr)
library(ggplot2)
library(ggthemes)

setwd('~/Code Projects/jasonpbecker.github.com/EDUC1160/')
slidify(inputFile="educ2350.Rmd", outputFile="educ2350.html")

