title: EDUC1160 Midterm 2
author: Jason P. Becker
email: jason_becker@brown.edu
date: 2013-04-08
keywords: EDUC1160, Brown_University, teaching, exam, midterm, boatman

# EDUC1160: Evaluating the Impact of Social Programs
# Exam 2

## Acknowledgement
This exam extensivesly uses materials provided by Angela Boatman from the Spring 2010 section of EDUC2360.

## Instructions

1. Answers can be submitted as .docx, .pdf, .txt, .md, .mmd, or .html. Please name your file submission last name-underscore-first initial. So Jason Becker would submit becker_j.docx.  

2. There is no maximum or minimum constraints for your answers to any questions. Please be as specific, complete, AND brief as possible in your answers.  Some questions can be answered with a very few words; others will require more explanation.

3. Be sure to save your renamed file repeatedly as you work so that you do not lose your work in the case of a computer gliltch. When you finish, save the file you will submit to me and save a second backup file. Allow yourself some time for computer glitches. The submission deadline on the exam is firm.

4. When you finish your exam you will submit it via email to jason_becker@brown.edu

5. As explained in class, you may use any notes or texts to help you with this exam, but you may not consult outside materials (for example, the internet) or anyone else about the exam from the time you access it until you submit your final answers. Methods Matter, the Canvas site, lectures slides from [](http://www.jsonbecker.com/EDUC1160), and your class notes are sufficient. If you are unsure if you are allowed to use a resource, ask.

6. You may email me with clarifying questions. Please be judicious with your clarifying questions. I reserve the right to forward your email and my response to the entire class or post on Canvas so as to assure that everyone has equal information whne completing this exam.

7. Finally, be sure to "sign" the Honor Statement at the end of the exam.

## I. Experimental Design

1. What is meant by the term “counterfactual” in the context of program evaluation?	What is the relationship between the counterfactual and the control group in an experimental program evaluation?
2. Identify one common threat to the internal validity of experimental evaluations and explain how it can result in biased estimates of program impacts.  Give an example to illustrate your point.
3. You want to evaluate a job training program which seeks to increase the earnings of program participants.  Assume an experimental evaluation with treatment and control groups of 100 people each.  What is the largest standard deviation in earnings that will ensure that you still detect an impact on earnings of at least a $250 increase with an 85 percent chance of rejecting the null at an alpha level of 0.01 with a one-tailed test?  Show your work.

## II. Interpreting Regressions
The questions in this section are all based on the first panel of Table 2 from the paper “Understanding the Black-White test score gap in the first two years of school” by Roland Fryer and Steve Levitt, which is copied below.  Keep in mind that the dependent variable, math test score, has been standardized to have a mean of 0 and a standard deviation of 1 for the full ECLS sample. You do not need to have read this paper to answer the following questions.

![](images/educ1160midtermfryer.png "Table 2")

1. Based on these regression results: (1) how large is the raw black-white test score gap upon entry into Kindergarten? (2) how large is the raw black-Hispanic test score gap upon entry into Kindergarten?
2. Write out the regression equation that is being estimated in column (3).
3. In one sentence,  interpret the estimated coefficient on the variable “Age in kindergarten fall (in months)” in column (4)?  
4. Based on the estimates in column (4), how does the predicted mean test score of a student with 20 books in the home compare to the predicted mean test score of an otherwise identical student with 40 books in the home?  Show your work.
5.	The estimated coefficient on the variable “Black” changes from -0.638 in column (1) to -0.094 in column (4).  What does this change mean in substantive terms?
6.	Give an example of a policy-relevant research question that arises from these results, and explain how you might use qualitative research methods to answer your question.  

## III. Quasi-Experimental Design

1. To be a valid instrument, a variable must meet two conditions: relevance and exogeneity.

	a. Define both of these terms in your own words (i.e.- not copied directly from the lecture slides or readings).
	b. Which of these two conditions is testable in the data?
	c. How would you go about testing this condition?  Why can you test one and not the other?

2. In an OLS regression of experimental or quasi-experimental results, can you interpret the coefficients on all the variables (other than the treatment variable) as causal effects?  Why or why not?

3. What is the Local Average Treatment Effect?

4. In a difference-in-differences estimation, what does the comparison group measure?

## IV: Course Readings

Questions related to: Currie, J., & Morerri, E. (2003).  “Mother’s education and the intergenerational transmission of human capital: Evidence from college openings”.  *Quarterly Journal of Economics*, 118(4), 1495-1532.

1.	For what substantive purpose do Currie & Moretti (2003) employ an instrumental variable estimation strategy?  (i.e.- what problem are they trying to solve?)
2.	What is their instrument?
	
	a.	How do they measure it?
	b.	Do you think it is a good choice for an instrument?  Explain.

3.	Why do they include a dummy variable for the interaction of COUNTY*YEARBRTH in their model?  Is this the same thing as including county- by-year-of-birth fixed effects?  Why or why not?

Questions related to: Dynarski,  S.  (2003).  “Does  Aid  Matter?  Measuring  the  Effect  of  Student  Aid  on  College  Attendance  and  Completion.”  *American  Economic  Review*  93:1,  pp.  279-288.

4. What policy change does Dynarski use as a natural experiment?
5. In equation (2) \\(y_{i} = \alpha + \beta(Father Deceased_{i} x Before_{i}) + \delta Father Deceased_{i} + \theta Before_{i} + \nu_{i}\\), which coefficient represents the treatment effect?
6. In Table 2, what is the difference between model (1) and (2)? Why is model (2) the preferred estimate of the treatment effect?


## Honor Statement

“On my personal honor I certify that all of the answers on this exam are my own answers.  I further certify that I did not consult nor visit with anyone about this exam between the time I began the exam until I submitted my completed exam responses.  My signature is my typed name below.”

Electronic Signature: 


About how much time did you spend on this exam (in hours).  Ex: 4.5 hours.
Hours: 


